#!/usr/bin/env bash
# Summary: Show the current NodeJS version.

# Bomb out if we hit an error, ever
set -e

# Verbose output in debug mode
[ -n "$HSENV_DEBUG" ] && {
  set -x
}

if [ -z "${HSENV_VERSION}" ]; then
  export HSENV_VERSION_FILE="$(hsenv-version-file)"
  export HSENV_VERSION="$(hsenv-version-file-read "$HSENV_VERSION_FILE" || true)"
fi

version_exists() {
  local version="$1"
  [ -n "${version}" ] && \
    [ -d "${HSENV_ROOT}/versions/${version}" ]
}

no_versions() {
  [ -z "$(hsenv-versions)" ]
}

if [ -z "$HSENV_VERSION" ]; then
  echo "hsenv: couldn't find any version specified for use" >&2
  exit 1
elif version_exists "$HSENV_VERSION"; then
  echo "$HSENV_VERSION"
elif no_versions; then
  echo "hsenv: no versions of NodeJS are currently installed" >&2
  exit 1
else
  echo "hsenv: version \`$HSENV_VERSION' is not installed" >&2
  exit 1
fi
