#!/usr/bin/env bash
# Summary: Uninstall a version of NodeJS.
#
# Usage: hsenv uninstall <version>
#
# Versions should be in the form of vN.N.N

# Bomb out if we hit an error, ever
set -e

# Verbose output in debug mode
[ -n "$HSENV_DEBUG" ] && {
  set -x
}

# Pull the desired version out of ARGV
version="$1"
version_dir="$HSENV_ROOT/versions/$version"

if [ -d "$version_dir" ]; then
  rm -rf "$version_dir"
  echo "Uninstalled $version"
else
  echo "hsenv: version \`$version' isn't installed" >&2
  exit 1
fi

