#!/usr/bin/env bash
#
# Summary: Execute a command from a particular NodeJS version.
#
# Usage: hsenv exec <command> [<args>]
#
# Puts the current NodeJS version onto PATH and runs the specified command.

# Bomb out if we hit an error, ever
set -e

# Verbose output in debug mode
[ -n "$HSENV_DEBUG" ] && {
  set -x
}

# Set the current NodeJS version
if [ -z "$HSENV_VERSION" ]; then
  HSENV_VERSION="$(hsenv version)"

  # Couldn't infer from a file either
  if [ -z "$HSENV_VERSION" ]; then
    echo "hsenv: no \`HSENV_VERSION' configured" >&2
    exit 1
  fi
fi

# if the specified NodeJS version lacks this bin, bail
if [ ! -x "$HSENV_ROOT/versions/$HSENV_VERSION/bin/$1" ]; then
  echo "hsenv: \`$1' does not exist for $HSENV_VERSION" >&2

  for version in "$(hsenv versions)"; do
    if [ -x "$HSENV_ROOT/versions/$version/bin/$1" ]; then
      echo "  $version" >&2
    fi
  done

  exit 1
fi

export HSENV_VERSION

# Put our bindir onto PATH
bindir="$HSENV_ROOT/versions/$HSENV_VERSION/bin"

export PATH="$bindir:$PATH"

exec "$@"
