#!/usr/bin/env bash

# hsenv version
version="0.3.3"

# Bomb out if we hit an error, ever
set -e
export -n CDPATH

# Verbose output in debug mode
[ -n "$HSENV_DEBUG" ] && {
  set -x
}

# Helper functions
resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

# Set up HSENV_ROOT, location where everything lives

if [ -z "${HSENV_ROOT}" ]; then
  HSENV_ROOT="${HOME}/.hsenv"
else
  HSENV_ROOT="${HSENV_ROOT%/}"
fi

export HSENV_ROOT

# Jump into the HSENV_DIR
if [ -z "${HSENV_DIR}" ]; then
  HSENV_DIR="$(pwd)"
else
  cd "${HSENV_DIR}" 2>/dev/null || {
    echo "hsenv: cannot change working directory to \`$HSENV_DIR'"
    exit 1
  } >&2

  HSENV_DIR="$(pwd)"

  cd "$OLDPWD"
fi

export HSENV_DIR

# Pop the first argument, our subcommand
command="$1"

# Make sure we can find out utilities on PATH
bin_path="$(abs_dirname "$0")"
export PATH="${bin_path}":$PATH

case "$command" in
  "" | "-h" | "--help" )
    exec hsenv-help
    ;;

  "-v" | "--version" )
    echo "hsenv ${version}"
    exit
    ;;

  *)
    command_path="${bin_path}/hsenv-${command}"

    [ -x "${command_path}" ] || {
      echo "hsenv: no such command \`$command'" >&2
      exit 1
    }

    shift 1
    exec "$command_path" "$@"
    ;;
esac
