#!/usr/bin/env bash
# Summary: Install a version of GHC.
#
# Usage: hsenv install <version>
#
# Versions should be in the form of N.N.N
#
# Bomb out if we hit an error, ever
set -e

# Verbose output in debug mode
[ -n "$HSENV_DEBUG" ] && {
  set -x
}

# Pull the desired version out of ARGV
version="$1"
version_dir="$HSENV_ROOT/versions/$version"
cabal_install_version="1.16.0.2"

# stash the pwd
OLDPWD=$(pwd)

# Determine url to download from
platform="$(uname -s | tr '[:upper:]' '[:lower:]')"
if [ "$platform" = "darwin" ]; then
  platform="apple-darwin"
fi
arch="$(uname -m)"

build_dir="/tmp/hsenv-$version"
rm -rf $build_dir
mkdir -p $HSENV_ROOT/cache $build_dir $build_dir/ghc $build_dir/cabal-install

# Download and install GHC
download="http://www.haskell.org/ghc/dist/$version/ghc-$version-$arch-$platform.tar.bz2"
ghc_cache_file="$HSENV_ROOT/cache/ghc-$version-$arch-$platform.tar.bz2"
curl -sfC - -o $ghc_cache_file $download
cd $build_dir/ghc
tar jxf $ghc_cache_file --strip-components 1
./configure --prefix=$version_dir
make install

# Download and install cabal-install
cabal_install_url="http://hackage.haskell.org/packages/archive/cabal-install/$cabal_install_version/cabal-install-$cabal_install_version.tar.gz"
curl -s -f "$cabal_install_url" > $build_dir/cabal-install.tar.gz
cd $build_dir/cabal-install
tar zxf $build_dir/cabal-install.tar.gz --strip-components 1
$version_dir/bin/ghc-pkg init $build_dir/pkg
GHC_PACKAGE_PATH=$version_dir/lib/ghc-$version/package.conf.d:$build_dir/pkg \
  PATH=$version_dir/bin:$PATH PREFIX=$version_dir \
  sh ./bootstrap.sh --global

rm -rf $build_dir
chmod -R 755 $version_dir

echo "Installed $version"
cd $OLDPWD
