#!/usr/bin/env bash
# Summary: Detect the file that sets the current hsenv version

# Bomb out if we hit an error, ever
set -e

# Verbose output in debug mode
[ -n "$HSENV_DEBUG" ] && {
  set -x
}

find_local_version_file() {
  local root="$1"
  while [ -n "$root" ]; do
    if [ -e "${root}/.node-version" ]; then
      echo "${root}/.node-version"
      exit
    elif [ -e "${root}/.nvm-version" ]; then
      echo "${root}/.nvm-version"
      exit
    fi
    root="${root%/*}"
  done
}

find_local_version_file "$HSENV_DIR"
[ "$HSENV_DIR" = "$PWD" ] || find_local_version_file "$PWD"

global_version_file="${HSENV_ROOT}/version"

if [ -e "$global_version_file" ]; then
  echo "$global_version_file"
fi

