#!/usr/bin/env bash
#
# Summary: Set HSENV_VERSION for the lifetime of a shell.
#
# Usage: hsenv shell <version>
#        hsenv shell --unset|-u

# Bomb out if we hit an error, ever
set -e

# Verbose output in debug mode
[ -n "$HSENV_DEBUG" ] && {
  set -x
}

version_installed() {
  local v="$1"
  [ -d "${HSENV_ROOT}/versions/${v}" ]
}

# Set the version
version="$1"

case "$version" in
  "")
    if [ -z "$HSENV_VERSION" ]; then
      echo "hsenv: no shell version configured" >&2
      exit 1
    else
      echo "echo \"$HSENV_VERSION\""
    fi
    ;;

  "-u" | "--unset")
    echo "unset HSENV_VERSION"
    ;;

  *)
    export HSENV_VERSION="$version"

    if version_installed "$version"; then
      echo "export HSENV_VERSION=\"${version}\""
    else
      echo "hsenv: version \`${version}' is not installed" >&2
      exit 1
    fi
    ;;
esac
